config/routes.rb
Rails.application.routes.draw do
  root 'employees#index'

  resources :employees
  resources :bills, only: [:new, :create, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord
  self.inheritance_column = 'not_sti'

  belongs_to :employee

  TYPES = %w(food travel others).freeze

  validates :amount, numericality: { greater_than: 0 }
  validates :type, presence: true, inclusion: { in: TYPES }

  private

  def self.types
    TYPES
  end
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :employees, dependent: :destroy

  validates :name, presence: true
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :department
  has_many :bills, dependent: :destroy

  validates :first_name, :last_name, :email, :department_id, :designation, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: true

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  def new
    @bill = Bill.new
    @employees = Employee.all
  end
  
  def index
    @bills = Bill.includes(:employee).all
    @total_bills_count = @bills.count
    @total_bills_amount = @bills.sum(:amount)
  end

  def create
    @bill = Bill.new(bill_params)
    if @bill.save
      redirect_to bills_path, notice: 'Bill was successfully created.'
    else
      @employees = Employee.all
      render :new
    end
  end

  private

  def bill_params
    params.require(:bill).permit(:amount, :type, :employee_id)
  end
end
# class BillsController < ApplicationController
#   def index
#     @bills = Bill.includes(employee: :department).all
#   end
# end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    @employees = Employee.all
  end

  def new
    @employee = Employee.new
    @departments = Department.all
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      redirect_to employees_path, notice: 'Employee was successfully created.'
    else
      @departments = Department.all
      render :new
    end
  end
  def show
    set_employee
  end
  def edit
    @employee = Employee.find(params[:id])
    @departments = Department.all
  end

  def update
    @employee = Employee.find(params[:id])
    if @employee.update(employee_params)
      redirect_to employees_path, notice: 'Employee was successfully updated.'
    else
      @departments = Department.all
      render :edit
    end
  end

  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy
    redirect_to employees_path, notice: 'Employee was successfully deleted.'
  end

  private
  def set_employee
    @employee = Employee.find(params[:id])
  end
  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :email, :department_id, :designation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/bills/index.html.erb
<br/>
<h1>Submitted Bills</h1>
<br/>
<h3>Total Bill: <%= number_to_currency(@total_bills_amount, unit: '₹', format: '%u%n') %></h3>
<h4>Total Bills Submitted: <%= @total_bills_count %></h4>




<br/>
<table class="table table-striped table-hover">
  <thead class="table-dark g-4">
    <tr>
      <th>Type</th>
      <th>Amount</th>
      <th>Date of Submission</th>
      <th>Submitted By</th>
      <th>Department</th>
    </tr>
  </thead>
  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= bill.type %></td>
        <td><%= bill.amount %></td>
        <td><%= bill.created_at.strftime("%Y-%m-%d") %></td>
        <td><%= bill.employee.full_name %></td>
        <td><%= bill.employee.department.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br/>
<%= link_to 'New Bill', new_bill_path, class: "btn btn-primary" %>
<%= link_to 'Back', employees_path,  class: "btn btn-secondary" %>

app/views/bills/new.html.erb
<br/>

<h1>New Bill</h1>
<br/>
<%= form_with(model: @bill, local: true) do |form| %>
  <% if @bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>
      <ul>
        <% @bill.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row g-3 ">
  <div class="field form-group col-md-4">
    <%= form.label :type ,class: "form-label" %>
    <%= form.collection_select :type, Bill::TYPES.map { |type| [type, type] }, :first, :last, { prompt: 'Select Bill Type' }, { class: 'form-select' } %>

  </div>

  <div class="field form-group col-md-4">
    <%= form.label :amount ,class: "form-label" %>
    <div class="input-group" >
          <span class="input-group-text" id="inputGroupPrepend">₹</span>

    <%= form.number_field :amount, class: "form-control", step: 0.01 %>
    </div>
  </div>

  <div class="field form-group col-md-8">
    <%= form.label :employee_id, "Employee" ,  { class: 'form-label' }%>
    <%= form.collection_select :employee_id, @employees, :id, :full_name, { prompt: 'Select an Employee' }, { class: 'form-select' } %>
  </div>
  <br/>
  <br/>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary'%>
  </div>
  </div>
<% end %>
<br/>
<%= link_to 'Back', bills_path, class: "btn btn-secondary" %>

app/views/employees/edit.html.erb
<br/>
<h1>Edit Employee</h1>

<%= form_with(model: @employee, local: true) do |form| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h3>
      <ul>
        <% @employee.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row g-3 ">

  <div class="field form-group col-md-4">
    <%= form.label :first_name ,class: "form-label" %>
    <%= form.text_field :first_name , { class: 'form-control' }%>
  </div>

  <div class="field form-group col-md-4">
    <%= form.label :last_name ,class: "form-label"  %>
    <%= form.text_field :last_name , { class: 'form-control' }%>
  </div>

  <div class="field form-group col-md-4">
    <%= form.label :email ,class: "form-label" %>
        <div class="input-group" >
          <span class="input-group-text" id="inputGroupPrepend">@</span>

    <%= form.email_field :email , { class: 'form-control' }%>
    </div>
  </div>

  <div class="field form-group col-md-4">
    <%= form.label :designation,class: "form-label"  %>
    <%= form.text_field :designation , { class: 'form-control' }%>
  </div>

  <div class="field form-group col-md-4">
    <%= form.label :department ,class: "form-label" %>
  <%= form.collection_select :department_id, @departments, :id, :name, { prompt: 'Select a Department' }, { class: 'form-select' } %>

  </div>
    <br/>
  <div class="actions">
    <%= form.submit class: "btn btn-primary"  %>
  </div>
  </div>
<% end %>
<br/>
<%= link_to 'Back', employees_path,  class: "btn btn-secondary" %>

app/views/employees/index.html.erb
<br/>
<h1>Welcome to the Employee Reimbursement Portal</h1>

<p>This is the landing page for the Employee Reimbursement Portal. From here, you can manage employees and bills.</p>

<ul>
  <li><%= link_to 'Create new Bill', new_bill_path %></li>
  <li><%= link_to 'View submitted bills', new_employee_path %></li>
  <li><%= link_to 'Add Employee', bills_path %></li>

</ul>
<br/>
<h2>Employee List</h2>
<br/>
<table class="table table-striped table-hover">
  <thead class="table-dark">
    <tr>
      <th>Full Name</th>
      <th>Designation</th>
      <th>Email</th>
      <th>Department</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.full_name %></td>
        <td><%= employee.designation %></td>
        <td><%= employee.email %></td>
        <td><%= employee.department.name %></td>
        <td> 
<%= link_to 'Edit', edit_employee_path(employee), class: "btn btn-primary" %> &nbsp;&nbsp; <%= link_to 'Delete', employee_path(employee), class: "btn btn-outline-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Employee', new_employee_path , class: "btn btn-primary"%>

app/views/employees/new.html.erb
<br/>
<h1>New Employee</h1>

<%= form_with(model: @employee, local: true) do |form| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>
      <ul>
        <% @employee.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row g-3 ">

  <div class="field form-group col-md-4">
    <%= form.label :first_name ,class: "form-label" %>
    <%= form.text_field :first_name , { class: 'form-control' }%>
  </div>

  <div class="field form-group col-md-4">
    <%= form.label :last_name ,class: "form-label"  %>
    <%= form.text_field :last_name , { class: 'form-control' }%>
  </div>

  <div class="field form-group col-md-4">
    <%= form.label :email ,class: "form-label" %>
        <div class="input-group" >
          <span class="input-group-text" id="inputGroupPrepend">@</span>

    <%= form.email_field :email , { class: 'form-control' }%>
    </div>
  </div>

  <div class="field form-group col-md-4">
    <%= form.label :designation,class: "form-label"  %>
    <%= form.text_field :designation , { class: 'form-control' }%>
  </div>

  <div class="field form-group col-md-4">
    <%= form.label :department ,class: "form-label" %>
  <%= form.collection_select :department_id, @departments, :id, :name, { prompt: 'Select a Department' }, { class: 'form-select' } %>

  </div>
    <br/>
  <div class="actions">
    <%= form.submit class: "btn btn-primary"  %>
  </div>
  </div>
<% end %>
<br/>
<%= link_to 'Back', employees_path,  class: "btn btn-secondary" %>

app/views/employees/show.html.erb
<h1><%= @employee.full_name %></h1>

<p>
  <strong>Email:</strong>
  <%= @employee.email %>
</p>

<p>
  <strong>Department:</strong>
  <%= @employee.department.name if @employee.department %>
</p>

<p>
  <strong>Designation:</strong>
  <%= @employee.designation %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee), class: "btn btn-primary" %> |
<%= link_to 'Back', employees_path , class: "btn btn-secondary" %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Employee Reimbursement</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
    <li class="nav-item">
      <%= link_to 'Employee', root_path, class: 'nav-link' %>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        Bill
      </a>
      <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
        <li>
          <%= link_to 'Create Bill', new_bill_path, class: 'dropdown-item' %>
        </li>
        <li>
          <%= link_to 'View Bills', bills_path, class: 'dropdown-item' %>
        </li>
      </ul>
    </li>
  </ul>
</div>


  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>EmployeeReimbursementPortal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    
    <%= render 'layouts/header' %>

    <div class="container">
    <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>